### PR TITLE
Create `dev` directory for holding development work, alongside basic Arduino demo of ENC28J60

### PR DESCRIPTION
**Pull request by bluebandit21**

### CODE REVIEW

**Comment by Santa-Bunny** [comment]
I want to delete the BLUEBANDITYOUMONSTER.md first before merging

**Comment by Santa-Bunny** [comment]
As well. please rename dev/DEV.md to dev/README.md
It allows git to recognize it as a display markdown file and will display it when entering the /dev folder.
My other worry is adding a dev/ folder to the dev branch will make merging with main more difficult unless you plan to have that visible under main, and just be a "pls no touch this folder" type of deal

**Review by Santa-Bunny — COMMENTED** [review]
I worry about adding a dev folder to the dev branch as it makes it more difficult to merge with main under version changes. Other than that I approve the request to merge with the changes I made:
Deleting BLUEBANDITYOUMONSTER
rename dev/DEV.md to dev/README.md for git recognition

**Comment by Santa-Bunny** [comment]
unless you plan to have that visible in the main branch, and just be a "pls no touch this folder" type of deal

**Comment by bluebandit21** [comment]
> unless you plan to have that visible in the main branch, and just be a "pls no touch this folder" type of deal
was kind of what I was imagining if it seems reasonable?

I guess the question is whether it's useful to still have the old Arduino-specific / barebones MSP430 development experiment stuff around indefinitely.
Maybe the answer to that is no, it isn't.

**Comment by Santa-Bunny** [comment]
We can always remove it in a later version but it at least allows us to clean up the forks and realistically if someone came across the project now, they'd want access to the starter files in Arduino

**Pull request merged**
