### PR TITLE
Porting FreeRTOS, initSPI, and clock setup for the MSP430FR2355 processor

### PR DESCRIPTION
**Pull request by tomputer-g**
The RTOS_FR2355 project is a proven working FreeRTOS port for our uC, as shown by the deferred interrupt example shown during demo 1. 

main.c includes all relevant setup packaged into nice functions (initSPI, prvSetup, etc.) as well as some Hooks used by FreeRTOS in case things go south. It references and calls the deferred_interrupt.c main function where it demonstrates deferred interrupts (on the dev board, using red and green LEDs).

Setup: prvSetup() sets up all SPI lines (A1 disabled by default since that is also used for debugging) as well as both onboard LEDs and buttons. It calls clockSetup() which by our discussion sets up the CPU at 16MHz and SPI lines at 8MHz.
initSPI() sets up a given SPI line to 8MHz master, and should include a commit that changes the polarity setting to work with our devices.

FreeRTOSConfig.h is where we define things like tick speed, usage of different functions, etc. We will need to disable preemption and fine-tune other things here later.

Nothing besides these above three files should need to be changed. This includes the FreeRTOS port as well as Driverlib.

### CODE REVIEW

**Comment by tomputer-g** [comment]
Since driverlib exists in this project and (I think) we only need it within the project, we can remove /dev/driverlib/* after this, unless we need it to specifically be there

**Review by Santa-Bunny — CHANGES_REQUESTED** [review]
In FreeRTOS_Source I would recommend deleting the .github folder. It contains items for submitting to the Source code of Free_RTOS, I don't see a use to bring it into a forked section that has no affiliation with Amazon. The licensing is in a separate section anyway.

In FreeRTOS_Source/build/.cmake/api/v1/query/client-integration-vscode/
cache-v2, cmakeFiles-v1, and codemodel-v2 are all empty files, unless they are necessary for the api to run, I would recommend deleting them as well for a clean codebase.

**Comment by tomputer-g** [comment]
Fair and agreed, I would also ask @bluebandit21 to see if there are other files that should be purged before this port completes. I believe he said we can either rebase it so that it was never committed in the first place, or do some other thing with it.

**Comment by tomputer-g** [comment]
In the same vein, I probably need to look at the gitignore together with one of yall too, since all we have now is /Debug/ and I'm sure at least some other files exist that we don't care about.

**Comment by tomputer-g** [comment]
Worked with @bluebandit21 to untrack and remove files with rebase.
Removing files:
.launches/RTOS_FR2355_new.launch - not used, previous artifact of renaming
FreeRTOS_Source/.github - see Santa’s comment
FreeRTOS_Source/build - cmake build artifacts (and not even cleaned nor built when CCS builds?)
ReadMe_Instructions.url - was for FR5969 (pre-port)

Untrack + gitignore:
targetConfigs/*
.settings/*

Also fixing main.c for a missing closing curly brace.

**Review by Santa-Bunny — APPROVED** [review]

**Pull request merged**
